version: "3"

services:
  nginx:
    image: nginx
    volumes:
      # - ./nginx/nginx-templates:/etc/nginx/templates
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/ssl/certs/opencast
    ports:
      - "80:80"
      - "443:443"
      # networks:
      #   opencast-network:
        #     ipv4_address: 172.16.0.7
    networks:
      - nginx-network

networks:
  nginx-network:
    name: external-opencast-moodle-network
    ipam:
      config:
        - subnet: 172.16.0.0/24