version: "3"

services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.2
    ports:
      - "5601:5601"
    networks:
      kibana-network:
        ipv4_address: 172.16.0.9
    hostname: kibana.opencast-dsa.local 


networks:
  kibana-network:
    name: external-opencast-moodle-network